language: python

python:
  - 3.4

install:
    yes | sudo add-apt-repository ppa:zoogie/sdl2-snapshots;
    yes | sudo add-apt-repository ppa:gstreamer-developers/ppa;
    sudo apt-get update;
    sudo apt-get install libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libsdl2-mixer-dev;
    sudo apt-get install libgstreamer1.0-dev gstreamer1.0-alsa gstreamer1.0-plugins-base;
    sudo apt-get install python-dev libsmpeg-dev libswscale-dev libavformat-dev libavcodec-dev libjpeg-dev libtiff4-dev libX11-dev libmtdev-dev;
    sudo apt-get install python-setuptools build-essential libgl1-mesa-dev libgles2-mesa-dev;
    sudo apt-get install xvfb pulseaudio;
    pip install --upgrade Cython==0.21.2 pillow nose coveralls;
    pip install -r requirements.txt;
    garden install filebrowser;

before_script:
    export DISPLAY=:99.0;
    /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1280x720x24 -ac +extension GLX;
    export PYTHONPATH=$PYTHONPATH:$(pwd);
    mkdir -p ~/.config;

script:
  - make style
  - make test

notifications:
  irc:
    channels:
      - chat.freenode.net#kivy-dev
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
